name: Tests
on: [pull_request]

permissions: {}

jobs:
  tests:
    name: Run PHP Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.5', '8.6']
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Install php
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          coverage: none

      - name: Install dependencies
        run: composer update --dev --no-interaction --prefer-dist --no-progress --no-suggest --ansi

      - name: Run phpunit
        run: |
          ./vendor/bin/phpunit